services:
  remote-wakeonlan:
    container_name: remote-wakeonlan
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: ecole96/remote-wakeonlan-1.0.0
    network_mode: host
    restart: unless-stopped
